### ISSUE TITLE
Datacite didnt work on RedHat7

### ISSUE THREAD

**Issue by patrickmcsweeney** [eprintsug/DataCiteDoi#14]
Built an EPM using gitaar from eprints UG. It seems to work except that the coin doi event fails.

Thu Jun  1 15:11:03 2017 [soton] PID=4501 Metadata response from datacite api: 501: LWP will support https URLs if the LWP::Protocol::https module
is installed.

Thu Jun  1 15:11:03 2017 [soton] PID=4501 BTW the $doi was:
10.5072/SOTON/B0100

i have perl-Crypt-SSLeay installed and LWP

it looks like a dependancy issue because:

perl -e "use LWP::Protocol::https;"
Can't locate LWP/Protocol/https.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at -e line 1.
BEGIN failed--compilation aborted at -e line 1.

but perl-Crypt-SSLeay should provide this...

**Comment by goetzk** [comment]
Hi @patrickmcsweeney ,

A look on a RHEL 7.5 system suggests you're actually after this LWP plugin:
perl-LWP-Protocol-https.noarch : Provide HTTPS support for LWP::UserAgent

Perhaps open a PR to add it to the dependencies list in the README?

Karl.

**Comment by goetzk** [comment]
I just noticed https://wiki.eprints.org/w/index.php?title=Installing_EPrints_on_RHEL/Fedora/CentOS&diff=prev&oldid=12408 mentions perl-LWP-Protocol-https for this plugin; its likely the readme is outdated so I will update it for 2.2
