### ISSUE TITLE
Allow mapping functions to fallback if no value is present

### ISSUE THREAD

**Issue by cziaarm** [eprintsug/DataCiteDoi#18]
In this loop: https://github.com/eprintsug/DataCiteDoi/blob/master/lib/plugins/EPrints/Plugin/Export/DataCiteXML.pm#L62-L68

A vvalue must exist before a mapping function is called. This means that there is no way to cascade through EPrints field until here is a suitable candidate for the Datacite element.

eg If eprint.creators is not set then use eprint.corp_creators (when making a datacite.Creator)

Delegate all the value checking to the mapping subs so that they can be modified to introduce 
 the ability to cascade through Eprints metadata where appropriate.

**Comment by geekscruff** [comment]
@cziaarm @BorysFeldman and I agreed that we thing both creators and corp_creators should be added ... currently corp_creators is not processed. So not so much a fallback as a concatenation.

**Comment by cziaarm** [comment]
#fd41e34efc7cc00a529c8f45ad22bb2b376d7768
