### ISSUE TITLE
DataCite XML schema

### ISSUE THREAD

**Issue by photomedia** [eprintsug/DataCiteDoi#2]
The following error in DataCite XML:

Metadata response from datacite api: 400: [xml] xml error: cvc-complex-type.3.2.2: Attribute 'schemeURI' is not allowed to appear in element 'nameIdentifier'.

**Comment by BorysFeldman** [comment]
Hi Thomas,
I have updated the schema version to 4.0, before it was set as 2.2 .So now DataCite should not reject it. Please let us know if there are any further issues.
https://github.com/eprintsug/DataCiteDoi/commit/aceb6403be078cc3b6fc72f892984ae76f4188d8
