### ISSUE TITLE
DataCite XML schema

### ISSUE THREAD

**Issue by photomedia** [eprintsug/DataCiteDoi#3]
DataCite rejects the XML due to an error with an unexpected _givenName_ and _familyName_  elements in the XML.  The declared schema doesn’t allow for _givenName_ and _familyName_  as XML elements.
See:  http://schema.datacite.org/meta/kernel-2.2/metadata.xsd

**Comment by photomedia** [comment]
Another error related to schema conformity: Metadata response from datacite api: 400: [xml] xml error: cvc-complex-type.3.2.2: Attribute 'xml:lang' is not allowed to appear in element 'title'.

**Comment by BorysFeldman** [comment]
Hi Thomas,
I have updated the schema version to 4.0, before it was set as 2.2 so DataCite should not reject it. Please let us know if there are any further issues.
https://github.com/eprintsug/DataCiteDoi/commit/aceb6403be078cc3b6fc72f892984ae76f4188d8
