### ISSUE TITLE
Using a hash as a reference is depracated at (eval) line .., <DATA> line...

### ISSUE THREAD

**Issue by photomedia** [eprintsug/DataCiteDoi#6]
the following section in cfg/cfg.d/z_datacite.pl: 

if($c->{datacitedoi}{auto_coin}){
[...]

Looks to be causing three of the following errors:
Using a hash as a reference is deprecated at (eval 164) line 95, <DATA> line 747.
Using a hash as a reference is deprecated at (eval 164) line 99, <DATA> line 747.
Using a hash as a reference is deprecated at (eval 164) line 100, <DATA> line 747.

When commenting out this function, errors go away.

**Comment by cziaarm** [comment]
I think it is these three:

https://github.com/eprintsug/DataCiteDoi/blob/402886d09c200a7cd006afdb6d3f3acc61e75a53/cfg/cfg.d/z_datacitedoi.pl#L95
https://github.com/eprintsug/DataCiteDoi/blob/402886d09c200a7cd006afdb6d3f3acc61e75a53/cfg/cfg.d/z_datacitedoi.pl#L99
https://github.com/eprintsug/DataCiteDoi/blob/402886d09c200a7cd006afdb6d3f3acc61e75a53/cfg/cfg.d/z_datacitedoi.pl#L100

Which look to be treating the %params hash as though it were a hashref

Should be either getting a hashref or they should use $params{repository} and $params{dataobj}

Thanks,

Rory
