### ISSUE TITLE
DataCiteXML should use eprintdoifield from config file

### ISSUE THREAD

**Issue by doertebange** [eprintsug/DataCiteDoi#7]
In line 48 in DataCiteXML $thisdoi is taken from "id_number", but in the config file you can change this, so something like
		my $eprintdoifield = $repo->get_conf( "datacitedoi", "eprintdoifield");
		my $thisdoi = $dataobj->get_value( $eprintdoifield );
would be better here.

**Comment by cziaarm** [comment]
True

https://github.com/eprintsug/DataCiteDoi/blob/402886d09c200a7cd006afdb6d3f3acc61e75a53/lib/plugins/EPrints/Plugin/Export/DataCiteXML.pm#L48

In one line?

my $thisdoi = $dataobj->get_value($repo->get_conf( "datacitedoi", "eprintdoifield"));

Thanks,

Rory

**Comment by cziaarm** [comment]
4fed4d0 closes this
